SELECT * FROM cars.car_dekho;
SELECT * FROM cars.car_dekho;
use cars;
-- READ DATA--
SELECT * FROM cars.car_dekho;
-- TOTAL CARS; TO GET A COUNT OF TOTAL RECORDS--
SELECT count(*) FROM cars.car_dekho;
-- THE MANAGER ASKS THE EMPOLYEE HOW MANY CARS WILL BE AVAILABLE IN 2023?--
SELECT YEAR, count(*) FROM cars.car_dekho WHERE YEAR = 2023;

-- THE MANAGER ASKS THE EMPOLYEE HOW MANY CARS WILL BE AVAILABLE IN 2020,2021,2022?--
SELECT YEAR,count(*) FROM cars.car_dekho WHERE YEAR = 2020; #-> 74
SELECT YEAR,count(*) FROM cars.car_dekho WHERE YEAR = 2021; #-> 7
SELECT YEAR,count(*) FROM cars.car_dekho WHERE YEAR = 2022; #-> 7
-- GROUP BY--
SELECT YEAR,count(*) FROM cars.car_dekho WHERE YEAR IN (2020,2021,2022,2023) GROUP BY YEAR;

-- PRINT THE TOTAL OF ALL CARS BY YEAR--
select YEAR, count(*) FROM cars.car_dekho GROUP BY YEAR;

-- HOW MANY DIESEL CARS ARE AVAILABLE IN 2020?--
 SELECT count(*) FROM cars.car_dekho WHERE YEAR = 2020 AND FUEL = "DIESEL"; #-> 20
 
 -- HOW MANY PETROL CARS ARE AVAILABLE IN 2020?--
 SELECT count(*) FROM cars.car_dekho WHERE YEAR = 2020 AND FUEL = "PETROL"; #->51
 
 -- PRINT THE TOTAL OF ALL FUEL CARS BY ALL YEAR --
 SELECT YEAR,count("PETROL") FROM cars.car_dekho WHERE FUEL = "PETROL" group by YEAR;
 SELECT YEAR,count("DIESEL") FROM cars.car_dekho WHERE FUEL = "DIESEL" group by YEAR;
 SELECT YEAR,count("CNGL") FROM cars.car_dekho WHERE FUEL = "CNG" group by YEAR;

-- THERE WERE MORE THEN 100 CARS IN YEAR , WHICH YEAR HAVE MORE THAN 100 CARS?--
SELECT YEAR, count(*) FROM  cars.car_dekho group by YEAR HAVING COUNT(*) > 100;

-- ALL CARS COUNT DETAILS BETWEEN 2015 TO 2023 --
SELECT count(*)  FROM cars.car_dekho WHERE YEAR between 2015 AND 2023; SELECT * FROM cars.car_dekho;
use cars;
-- READ DATA--
SELECT * FROM cars.car_dekho;
-- TOTAL CARS; TO GET A COUNT OF TOTAL RECORDS--
SELECT count(*) FROM cars.car_dekho;
-- THE MANAGER ASKS THE EMPOLYEE HOW MANY CARS WILL BE AVAILABLE IN 2023?--
SELECT YEAR, count(*) FROM cars.car_dekho WHERE YEAR = 2023;

-- THE MANAGER ASKS THE EMPOLYEE HOW MANY CARS WILL BE AVAILABLE IN 2020,2021,2022?--
SELECT YEAR,count(*) FROM cars.car_dekho WHERE YEAR = 2020; #-> 74
SELECT YEAR,count(*) FROM cars.car_dekho WHERE YEAR = 2021; #-> 7
SELECT YEAR,count(*) FROM cars.car_dekho WHERE YEAR = 2022; #-> 7
-- GROUP BY--
SELECT YEAR,count(*) FROM cars.car_dekho WHERE YEAR IN (2020,2021,2022,2023) GROUP BY YEAR;

-- PRINT THE TOTAL OF ALL CARS BY YEAR--
select YEAR, count(*) FROM cars.car_dekho GROUP BY YEAR;

-- HOW MANY DIESEL CARS ARE AVAILABLE IN 2020?--
 SELECT count(*) FROM cars.car_dekho WHERE YEAR = 2020 AND FUEL = "DIESEL"; #-> 20
 
 -- HOW MANY PETROL CARS ARE AVAILABLE IN 2020?--
 SELECT count(*) FROM cars.car_dekho WHERE YEAR = 2020 AND FUEL = "PETROL"; #->51
 
 -- PRINT THE TOTAL OF ALL FUEL CARS BY ALL YEAR --
 SELECT YEAR,count("PETROL") FROM cars.car_dekho WHERE FUEL = "PETROL" group by YEAR;
 SELECT YEAR,count("DIESEL") FROM cars.car_dekho WHERE FUEL = "DIESEL" group by YEAR;
 SELECT YEAR,count("CNGL") FROM cars.car_dekho WHERE FUEL = "CNG" group by YEAR;

-- THERE WERE MORE THEN 100 CARS IN YEAR , WHICH YEAR HAVE MORE THAN 100 CARS?--
SELECT YEAR, count(*) FROM  cars.car_dekho group by YEAR HAVING COUNT(*) > 100;

-- ALL CARS COUNT DETAILS BETWEEN 2015 TO 2023 --
SELECT count(*)  FROM cars.car_dekho WHERE YEAR between 2015 AND 2023; 

-- END --